# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
#
# SPDX-License-Identifier: GPL-3.0-only
---
name: SQAaaS

on:
  push:
    branches: [main]

jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies with pipenv
        run: pip install pipenv && pipenv install --dev

      - name: Step definition for validating the workflow
        uses: eosc-synergy/sqaaas-step-action@v1
        with:
          name: pytest-step
          tool: pytest
          test_path: ./tests

      - name: Print out payload
        run: cat pytest-step.json

      - name: SQAaaS assessment with unit testing (QC.Uni) step
        uses: eosc-synergy/sqaaas-assessment-action@v2
        with:
          qc_uni_steps: pytest-step


          
