# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
#
# SPDX-License-Identifier: GPL-3.0-only
---
name: SQAaaS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pipenv and convert to requirements.txt
        run: |
          pip install pipenv
          pipenv lock -r -d > requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Step definition for validating the workflow
        uses: eosc-synergy/sqaaas-step-action@v1
        with:
          name: pytest-step
          tool: pytest
          test_path: ./tests
          # Optional: uncomment if using a specific container
          # container: ghcr.io/intertwin-eu/dask-flood-mapper:latest

      - name: Print out payload
        run: cat pytest-step.json

      - name: SQAaaS assessment with unit testing (QC.Uni) step
        uses: eosc-synergy/sqaaas-assessment-action@v2
        with:
          qc_uni_steps: pytest-step
